// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateLinkHandler(ReducerEventContext ctx, ulong source, ulong target);
        public event CreateLinkHandler? OnCreateLink;

        public void CreateLink(ulong source, ulong target)
        {
            conn.InternalCallReducer(new Reducer.CreateLink(source, target));
        }

        public bool InvokeCreateLink(ReducerEventContext ctx, Reducer.CreateLink args)
        {
            if (OnCreateLink == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateLink(
                ctx,
                args.Source,
                args.Target
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateLink : Reducer, IReducerArgs
        {
            [DataMember(Name = "source")]
            public ulong Source;
            [DataMember(Name = "target")]
            public ulong Target;

            public CreateLink(
                ulong Source,
                ulong Target
            )
            {
                this.Source = Source;
                this.Target = Target;
            }

            public CreateLink()
            {
            }

            string IReducerArgs.ReducerName => "create_link";
        }
    }
}
