// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteAllLinksHandler(ReducerEventContext ctx);
        public event DeleteAllLinksHandler? OnDeleteAllLinks;

        public void DeleteAllLinks()
        {
            conn.InternalCallReducer(new Reducer.DeleteAllLinks());
        }

        public bool InvokeDeleteAllLinks(ReducerEventContext ctx, Reducer.DeleteAllLinks args)
        {
            if (OnDeleteAllLinks == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteAllLinks(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteAllLinks : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "delete_all_links";
        }
    }
}
