// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteLinkHandler(ReducerEventContext ctx, ulong id);
        public event DeleteLinkHandler? OnDeleteLink;

        public void DeleteLink(ulong id)
        {
            conn.InternalCallReducer(new Reducer.DeleteLink(id));
        }

        public bool InvokeDeleteLink(ReducerEventContext ctx, Reducer.DeleteLink args)
        {
            if (OnDeleteLink == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteLink(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteLink : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;

            public DeleteLink(ulong Id)
            {
                this.Id = Id;
            }

            public DeleteLink()
            {
            }

            string IReducerArgs.ReducerName => "delete_link";
        }
    }
}
