// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateLinkHandler(ReducerEventContext ctx, ulong id, ulong source, ulong target);
        public event UpdateLinkHandler? OnUpdateLink;

        public void UpdateLink(ulong id, ulong source, ulong target)
        {
            conn.InternalCallReducer(new Reducer.UpdateLink(id, source, target));
        }

        public bool InvokeUpdateLink(ReducerEventContext ctx, Reducer.UpdateLink args)
        {
            if (OnUpdateLink == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateLink(
                ctx,
                args.Id,
                args.Source,
                args.Target
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateLink : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;
            [DataMember(Name = "source")]
            public ulong Source;
            [DataMember(Name = "target")]
            public ulong Target;

            public UpdateLink(
                ulong Id,
                ulong Source,
                ulong Target
            )
            {
                this.Id = Id;
                this.Source = Source;
                this.Target = Target;
            }

            public UpdateLink()
            {
            }

            string IReducerArgs.ReducerName => "update_link";
        }
    }
}
