// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Link
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "source")]
        public ulong Source;
        [DataMember(Name = "target")]
        public ulong Target;

        public Link(
            ulong Id,
            ulong Source,
            ulong Target
        )
        {
            this.Id = Id;
            this.Source = Source;
            this.Target = Target;
        }

        public Link()
        {
        }
    }
}
