// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LinksHandle : RemoteTableHandle<EventContext, Link>
        {
            public override string RemoteTableName => "links";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Link row) => row.Id;

                public IdUniqueIndex(LinksHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class SourceIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Link row) => row.Source;

                public SourceIndex(LinksHandle table) : base(table) { }
            }

            public readonly SourceIndex Source;

            public sealed class TargetIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Link row) => row.Target;

                public TargetIndex(LinksHandle table) : base(table) { }
            }

            public readonly TargetIndex Target;

            internal LinksHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Source = new(this);
                Target = new(this);
            }

            protected override object GetPrimaryKey(Link row) => row.Id;
        }

        public readonly LinksHandle Links;
    }

    public sealed class LinksCols
    {
        public global::SpacetimeDB.Col<Link, ulong> Id { get; }
        public global::SpacetimeDB.Col<Link, ulong> Source { get; }
        public global::SpacetimeDB.Col<Link, ulong> Target { get; }

        public LinksCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Link, ulong>(tableName, "id");
            Source = new global::SpacetimeDB.Col<Link, ulong>(tableName, "source");
            Target = new global::SpacetimeDB.Col<Link, ulong>(tableName, "target");
        }
    }

    public sealed class LinksIxCols
    {
        public global::SpacetimeDB.IxCol<Link, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Link, ulong> Source { get; }
        public global::SpacetimeDB.IxCol<Link, ulong> Target { get; }

        public LinksIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Link, ulong>(tableName, "id");
            Source = new global::SpacetimeDB.IxCol<Link, ulong>(tableName, "source");
            Target = new global::SpacetimeDB.IxCol<Link, ulong>(tableName, "target");
        }
    }
}
