// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateLinkArgs {
    pub source: u64,
    pub target: u64,
}

impl From<CreateLinkArgs> for super::Reducer {
    fn from(args: CreateLinkArgs) -> Self {
        Self::CreateLink {
            source: args.source,
            target: args.target,
        }
    }
}

impl __sdk::InModule for CreateLinkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
pub trait create_link {
    fn create_link(&self, source: u64, target: u64) -> __sdk::Result<()> {
        self.create_link_then(source, target, |_, _| {})
    }
    fn create_link_then(
        &self,
        source: u64,
        target: u64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_link for super::RemoteReducers {
    fn create_link_then(
        &self,
        source: u64,
        target: u64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateLinkArgs { source, target }, callback)
    }
}
