// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteAllLinksArgs {}

impl From<DeleteAllLinksArgs> for super::Reducer {
    fn from(_args: DeleteAllLinksArgs) -> Self {
        Self::DeleteAllLinks
    }
}

impl __sdk::InModule for DeleteAllLinksArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
pub trait delete_all_links {
    fn delete_all_links(&self) -> __sdk::Result<()> {
        self.delete_all_links_then(|_, _| {})
    }
    fn delete_all_links_then(
        &self,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_all_links for super::RemoteReducers {
    fn delete_all_links_then(
        &self,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteAllLinksArgs {}, callback)
    }
}
