// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteLinkArgs {
    pub id: u64,
}

impl From<DeleteLinkArgs> for super::Reducer {
    fn from(args: DeleteLinkArgs) -> Self {
        Self::DeleteLink { id: args.id }
    }
}

impl __sdk::InModule for DeleteLinkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
pub trait delete_link {
    fn delete_link(&self, id: u64) -> __sdk::Result<()> {
        self.delete_link_then(id, |_, _| {})
    }
    fn delete_link_then(
        &self,
        id: u64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_link for super::RemoteReducers {
    fn delete_link_then(
        &self,
        id: u64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteLinkArgs { id }, callback)
    }
}
