// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::link_type::Link;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `links`.
///
/// Obtain a handle from the [`LinksTableAccess::links`] method on [`super::RemoteTables`],
/// like `ctx.db.links()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.links().on_insert(...)`.
pub struct LinksTableHandle<'ctx> {
    imp: __sdk::TableHandle<Link>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `links`.
pub struct LinksTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for LinksTableAccessor {
    type Row = Link;
    type Handle<'db> = LinksTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.links()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `links`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LinksTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LinksTableHandle`], which mediates access to the table `links`.
    fn links(&self) -> LinksTableHandle<'_>;
}

impl LinksTableAccess for super::RemoteTables {
    fn links(&self) -> LinksTableHandle<'_> {
        LinksTableHandle {
            imp: self.imp.get_table::<Link>("links"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LinksInsertCallbackId(__sdk::CallbackId);
pub struct LinksDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for LinksTableHandle<'ctx> {
    type Row = Link;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Link> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for LinksTableHandle<'ctx> {
    type Row = Link;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Link> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LinksInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LinksInsertCallbackId {
        LinksInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LinksInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LinksDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LinksDeleteCallbackId {
        LinksDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LinksDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for LinksTableHandle<'ctx> {
    type InsertCallbackId = LinksInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LinksInsertCallbackId {
        LinksInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LinksInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for LinksTableHandle<'ctx> {
    type DeleteCallbackId = LinksDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LinksDeleteCallbackId {
        LinksDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LinksDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LinksUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LinksTableHandle<'ctx> {
    type UpdateCallbackId = LinksUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LinksUpdateCallbackId {
        LinksUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LinksUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for LinksTableHandle<'ctx> {
    type UpdateCallbackId = LinksUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LinksUpdateCallbackId {
        LinksUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LinksUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `links`,
/// which allows point queries on the field of the same name
/// via the [`LinksIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.links().id().find(...)`.
pub struct LinksIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Link, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LinksTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `links`.
    pub fn id(&self) -> LinksIdUnique<'ctx> {
        LinksIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LinksIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Link> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Link>("links");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Link>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Link>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Link`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait linksQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Link`.
    fn links(&self) -> __sdk::__query_builder::Table<Link>;
}

impl linksQueryTableAccess for __sdk::QueryTableAccessor {
    fn links(&self) -> __sdk::__query_builder::Table<Link> {
        __sdk::__query_builder::Table::new("links")
    }
}
