// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Link {
    pub id: u64,
    pub source: u64,
    pub target: u64,
}

impl __sdk::InModule for Link {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Link`.
///
/// Provides typed access to columns for query building.
pub struct LinkCols {
    pub id: __sdk::__query_builder::Col<Link, u64>,
    pub source: __sdk::__query_builder::Col<Link, u64>,
    pub target: __sdk::__query_builder::Col<Link, u64>,
}

impl __sdk::__query_builder::HasCols for Link {
    type Cols = LinkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LinkCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            target: __sdk::__query_builder::Col::new(table_name, "target"),
        }
    }
}

/// Indexed column accessor struct for the table `Link`.
///
/// Provides typed access to indexed columns for query building.
pub struct LinkIxCols {
    pub id: __sdk::__query_builder::IxCol<Link, u64>,
    pub source: __sdk::__query_builder::IxCol<Link, u64>,
    pub target: __sdk::__query_builder::IxCol<Link, u64>,
}

impl __sdk::__query_builder::HasIxCols for Link {
    type IxCols = LinkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LinkIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            source: __sdk::__query_builder::IxCol::new(table_name, "source"),
            target: __sdk::__query_builder::IxCol::new(table_name, "target"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Link {}
