// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateLinkArgs {
    pub id: u64,
    pub source: u64,
    pub target: u64,
}

impl From<UpdateLinkArgs> for super::Reducer {
    fn from(args: UpdateLinkArgs) -> Self {
        Self::UpdateLink {
            id: args.id,
            source: args.source,
            target: args.target,
        }
    }
}

impl __sdk::InModule for UpdateLinkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_link`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_link {
    /// Request that the remote module invoke the reducer `update_link` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_link:update_link_then`] to run a callback after the reducer completes.
    fn update_link(&self, id: u64, source: u64, target: u64) -> __sdk::Result<()> {
        self.update_link_then(id, source, target, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_link` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_link_then(
        &self,
        id: u64,
        source: u64,
        target: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_link for super::RemoteReducers {
    fn update_link_then(
        &self,
        id: u64,
        source: u64,
        target: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateLinkArgs { id, source, target }, callback)
    }
}
