// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateLinkArgs {
    pub id: u64,
    pub source: u64,
    pub target: u64,
}

impl From<UpdateLinkArgs> for super::Reducer {
    fn from(args: UpdateLinkArgs) -> Self {
        Self::UpdateLink {
            id: args.id,
            source: args.source,
            target: args.target,
        }
    }
}

impl __sdk::InModule for UpdateLinkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
pub trait update_link {
    fn update_link(&self, id: u64, source: u64, target: u64) -> __sdk::Result<()> {
        self.update_link_then(id, source, target, |_, _| {})
    }
    fn update_link_then(
        &self,
        id: u64,
        source: u64,
        target: u64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_link for super::RemoteReducers {
    fn update_link_then(
        &self,
        id: u64,
        source: u64,
        target: u64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateLinkArgs { id, source, target }, callback)
    }
}
