#!/usr/bin/env python3
"""Tests for the benchmark reporting pipeline implemented in ``out.py``.

These tests guard the automation that publishes benchmark results, so a broken
parser or README update is caught in CI instead of silently producing an empty
results table.

Run with:
    cd rust && python3 -m unittest test_out -v
"""

import os
import tempfile
import unittest

import out

# Minimal but realistic criterion bencher output: every operation for every
# benchmarked backend, plus noise lines criterion prints around the results.
SAMPLE_OUT_TXT = """
Gnuplot not found, using plotters backend
running 35 tests
test create/SpacetimeDB/1000 ... bench:   3,159,452,615 ns/iter (+/- 12,345)
test create/Doublets_United_Volatile/1000 ... bench:        84,823 ns/iter (+/- 1,000)
test create/Doublets_United_NonVolatile/1000 ... bench:        86,001 ns/iter (+/- 1,000)
test create/Doublets_Split_Volatile/1000 ... bench:        84,120 ns/iter (+/- 1,000)
test create/Doublets_Split_NonVolatile/1000 ... bench:        83,188 ns/iter (+/- 1,000)
test update/SpacetimeDB/1000 ... bench:    38,993,916 ns/iter (+/- 100)
test update/Doublets_United_Volatile/1000 ... bench:         1,484 ns/iter (+/- 10)
test update/Doublets_United_NonVolatile/1000 ... bench:         1,539 ns/iter (+/- 10)
test update/Doublets_Split_Volatile/1000 ... bench:           833 ns/iter (+/- 10)
test update/Doublets_Split_NonVolatile/1000 ... bench:           836 ns/iter (+/- 10)
test delete/SpacetimeDB/1000 ... bench:  1,989,558,566 ns/iter (+/- 100)
test delete/Doublets_United_Volatile/1000 ... bench:       143,527 ns/iter (+/- 100)
test delete/Doublets_United_NonVolatile/1000 ... bench:       153,180 ns/iter (+/- 100)
test delete/Doublets_Split_Volatile/1000 ... bench:       145,585 ns/iter (+/- 100)
test delete/Doublets_Split_NonVolatile/1000 ... bench:       143,649 ns/iter (+/- 100)
test query_all/SpacetimeDB/1000 ... bench:       943,914 ns/iter (+/- 100)
test query_all/Doublets_United_Volatile/1000 ... bench:            74 ns/iter (+/- 1)
test query_all/Doublets_United_NonVolatile/1000 ... bench:            77 ns/iter (+/- 1)
test query_all/Doublets_Split_Volatile/1000 ... bench:            78 ns/iter (+/- 1)
test query_all/Doublets_Split_NonVolatile/1000 ... bench:            77 ns/iter (+/- 1)
test query_by_id/SpacetimeDB/1000 ... bench:     8,801,871 ns/iter (+/- 100)
test query_by_id/Doublets_United_Volatile/1000 ... bench:           348 ns/iter (+/- 1)
test query_by_id/Doublets_United_NonVolatile/1000 ... bench:           348 ns/iter (+/- 1)
test query_by_id/Doublets_Split_Volatile/1000 ... bench:           348 ns/iter (+/- 1)
test query_by_id/Doublets_Split_NonVolatile/1000 ... bench:           348 ns/iter (+/- 1)
test query_by_source/SpacetimeDB/1000 ... bench:     8,729,692 ns/iter (+/- 100)
test query_by_source/Doublets_United_Volatile/1000 ... bench:           677 ns/iter (+/- 1)
test query_by_source/Doublets_United_NonVolatile/1000 ... bench:           493 ns/iter (+/- 1)
test query_by_source/Doublets_Split_Volatile/1000 ... bench:           422 ns/iter (+/- 1)
test query_by_source/Doublets_Split_NonVolatile/1000 ... bench:           408 ns/iter (+/- 1)
test query_by_target/SpacetimeDB/1000 ... bench:     8,742,366 ns/iter (+/- 100)
test query_by_target/Doublets_United_Volatile/1000 ... bench:           671 ns/iter (+/- 1)
test query_by_target/Doublets_United_NonVolatile/1000 ... bench:           487 ns/iter (+/- 1)
test query_by_target/Doublets_Split_Volatile/1000 ... bench:           411 ns/iter (+/- 1)
test query_by_target/Doublets_Split_NonVolatile/1000 ... bench:           411 ns/iter (+/- 1)
"""

README_TEMPLATE = f"""# Title

## Results

{out.README_START_MARKER}
> _Benchmark results will be generated by CI._
{out.README_END_MARKER}

## Conclusion
"""


def write(path, content):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    return path


class ParseResultsTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.path = write(os.path.join(self.tmp.name, "out.txt"), SAMPLE_OUT_TXT)

    def test_parses_every_operation_and_variant(self):
        results = out.parse_results(self.path)

        self.assertEqual(len(results), len(out.OPERATIONS))
        for operation, _label in out.OPERATIONS:
            measured = results[operation]
            self.assertEqual(
                sorted(measured),
                sorted(key for key, _label, _color in out.VARIANTS),
                f"missing variants for {operation}",
            )

    def test_parses_thousand_separators(self):
        results = out.parse_results(self.path)

        self.assertEqual(results["create"]["SpacetimeDB"], 3_159_452_615)
        self.assertEqual(results["create"]["Doublets_United_Volatile"], 84_823)

    def test_missing_file_yields_empty_results(self):
        results = out.parse_results(os.path.join(self.tmp.name, "absent.txt"))

        self.assertFalse(out.has_any_results(results))

    def test_unrelated_lines_are_ignored(self):
        path = write(
            os.path.join(self.tmp.name, "noise.txt"),
            "Benchmarking create/SpacetimeDB/1000: Warming up for 3.0000 s\n",
        )

        self.assertFalse(out.has_any_results(out.parse_results(path)))


class SpeedupFormattingTests(unittest.TestCase):
    def test_faster_than_baseline(self):
        self.assertEqual(out.format_speedup(100, 1000), "100 (10.0x faster)")

    def test_slower_than_baseline(self):
        self.assertEqual(out.format_speedup(1000, 100), "1000 (10.0x slower)")

    def test_missing_measurement(self):
        self.assertEqual(out.format_speedup(0, 1000), "N/A")

    def test_missing_baseline_reports_raw_value(self):
        self.assertEqual(out.format_speedup(100, 0), "100")


class ResultsTableTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        path = write(os.path.join(self.tmp.name, "out.txt"), SAMPLE_OUT_TXT)
        self.results = out.parse_results(path)
        self.table = out.format_results_table(self.results)

    def test_table_has_a_row_per_operation(self):
        rows = [line for line in self.table.splitlines() if line.startswith("|")]

        # header + separator + one row per operation
        self.assertEqual(len(rows), len(out.OPERATIONS) + 2)

    def test_header_lists_every_variant(self):
        header = self.table.splitlines()[0]

        for _key, label, _color in out.VARIANTS:
            self.assertIn(label, header)

    def test_doublets_cells_are_annotated_with_speedup(self):
        create_row = next(
            line for line in self.table.splitlines() if line.startswith("| Create")
        )

        # 3_159_452_615 / 84_823 = 37,247.6x
        self.assertIn("84823 (37247.6x faster)", create_row)
        self.assertIn("3159452615", create_row)

    def test_missing_measurements_render_as_not_available(self):
        partial = {operation: {} for operation, _label in out.OPERATIONS}
        partial["create"]["SpacetimeDB"] = 1000

        table = out.format_results_table(partial)
        create_row = next(
            line for line in table.splitlines() if line.startswith("| Create")
        )

        self.assertIn("N/A", create_row)


class ProvenanceTests(unittest.TestCase):
    def test_local_run_provenance(self):
        provenance = out.build_provenance(
            benchmark_links="1000",
            background_links="3000",
            generated_at="2026-01-01 00:00 UTC",
        )

        self.assertIn("2026-01-01 00:00 UTC", provenance)
        self.assertIn("1000 benchmarked links", provenance)
        self.assertIn("3000 background links", provenance)

    def test_github_actions_provenance_links_to_the_run(self):
        os.environ["GITHUB_REPOSITORY"] = "linksplatform/Comparisons.SpacetimeDBVSDoublets"
        os.environ["GITHUB_RUN_ID"] = "1234567890"
        self.addCleanup(os.environ.pop, "GITHUB_REPOSITORY", None)
        self.addCleanup(os.environ.pop, "GITHUB_RUN_ID", None)

        provenance = out.build_provenance(generated_at="2026-01-01 00:00 UTC")

        self.assertIn(
            "https://github.com/linksplatform/Comparisons.SpacetimeDBVSDoublets"
            "/actions/runs/1234567890",
            provenance,
        )


class ReadmeUpdateTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.readme = write(os.path.join(self.tmp.name, "README.md"), README_TEMPLATE)

    def read(self):
        with open(self.readme, "r", encoding="utf-8") as handle:
            return handle.read()

    def test_replaces_content_between_markers(self):
        self.assertTrue(out.update_readme(self.readme, "TABLE"))

        content = self.read()
        self.assertIn(f"{out.README_START_MARKER}\nTABLE\n{out.README_END_MARKER}", content)
        self.assertNotIn("will be generated by CI", content)
        self.assertIn("## Conclusion", content)

    def test_update_is_idempotent(self):
        out.update_readme(self.readme, "TABLE")

        self.assertFalse(out.update_readme(self.readme, "TABLE"))

    def test_special_regex_characters_survive_replacement(self):
        section = r"| Create | 100 (1.5x faster) \g<0> $1 |"

        out.update_readme(self.readme, section)

        self.assertIn(section, self.read())

    def test_missing_markers_raise(self):
        path = write(os.path.join(self.tmp.name, "no-markers.md"), "# Title\n")

        with self.assertRaises(ValueError):
            out.update_readme(path, "TABLE")


class MainTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.input = write(os.path.join(self.tmp.name, "out.txt"), SAMPLE_OUT_TXT)
        self.readme = write(os.path.join(self.tmp.name, "README.md"), README_TEMPLATE)
        self.results = os.path.join(self.tmp.name, "results.md")
        self.docs = os.path.join(self.tmp.name, "Docs")

    def test_writes_results_and_updates_readme(self):
        exit_code = out.main(
            [
                self.input,
                "--results",
                self.results,
                "--readme",
                self.readme,
                "--output-dir",
                self.tmp.name,
                "--docs-dir",
                self.docs,
            ]
        )

        self.assertEqual(exit_code, 0)
        with open(self.results, "r", encoding="utf-8") as handle:
            results_md = handle.read()
        self.assertIn("| Create", results_md)
        with open(self.readme, "r", encoding="utf-8") as handle:
            self.assertIn("| Create", handle.read())

    @unittest.skipUnless(out.HAS_MATPLOTLIB, "matplotlib is not installed")
    def test_generates_and_copies_charts(self):
        out.main(
            [
                self.input,
                "--results",
                self.results,
                "--output-dir",
                self.tmp.name,
                "--docs-dir",
                self.docs,
            ]
        )

        for chart in ("bench_rust.png", "bench_rust_log_scale.png"):
            self.assertTrue(os.path.exists(os.path.join(self.tmp.name, chart)), chart)
            self.assertTrue(os.path.exists(os.path.join(self.docs, chart)), chart)

    def test_empty_input_reports_failure(self):
        empty = write(os.path.join(self.tmp.name, "empty.txt"), "")

        self.assertEqual(out.main([empty, "--results", self.results]), 1)


if __name__ == "__main__":
    unittest.main()
